import pandas as pd
import matplotlib.pyplot as plt
import os

def plot_weight_comparison(csv_files, labels):
    """
    Loads multiple VR telemetry CSVs and plots their vertical kinematics 
    and power side-by-side for comparison.
    """
    print("Loading data and generating plots...")
    
    # Create a large figure with 4 stacked subplots
    fig, axs = plt.subplots(4, 1, figsize=(10, 14), sharex=True)
    fig.suptitle('Biomechanical Lift Comparison: Empty Hand vs Heavy Weight', fontsize=16, fontweight='bold')

    # Loop through each file and plot its data
    for file_path, label in zip(csv_files, labels):
        if not os.path.exists(file_path):
            print(f"Warning: Could not find {file_path}. Skipping...")
            continue
            
        # Load the CSV
        df = pd.read_csv(file_path)
        
        # Normalize time so every plot starts exactly at T=0.0 seconds
        t = df['timestamp'] - df['timestamp'].iloc[0]

        # Plot 1: Vertical Position (The shape of the lift)
        axs[0].plot(t, df['pos_y'], label=f'{label} kg', linewidth=2)
        
        # Plot 2: Vertical Velocity (The speed of the lift)
        axs[1].plot(t, df['vel_y'], label=f'{label} kg', linewidth=2)
        
        # Plot 3: Vertical Acceleration (The force applied)
        axs[2].plot(t, df['acc_y'], label=f'{label} kg', linewidth=2)
        
        # Plot 4: Mechanical Power Proxy (The energy burned)
        axs[3].plot(t, df['power'], label=f'{label} kg', linewidth=2)

    # --- Formatting the Subplots ---
    
    # Position
    axs[0].set_ylabel('Position Y (meters)')
    axs[0].set_title('Trajectory (Height over time)')
    axs[0].grid(True, linestyle='--', alpha=0.7)
    axs[0].legend()

    # Velocity
    axs[1].set_ylabel('Velocity Y (m/s)')
    axs[1].set_title('Speed Profile')
    axs[1].grid(True, linestyle='--', alpha=0.7)
    axs[1].legend()

    # Acceleration
    axs[2].set_ylabel('Acceleration Y (m/s²)')
    axs[2].set_title('Force / Acceleration')
    axs[2].grid(True, linestyle='--', alpha=0.7)
    axs[2].legend()

    # Power
    axs[3].set_ylabel('Power Proxy')
    axs[3].set_title('Calculated Mechanical Effort')
    axs[3].set_xlabel('Time (Seconds)')
    axs[3].grid(True, linestyle='--', alpha=0.7)
    axs[3].legend()

    # Clean up layout and display
    plt.tight_layout(rect=[0, 0.03, 1, 0.96])
    plt.show()

# ==========================================
# RUNNING THE SCRIPT
# ==========================================
if __name__ == "__main__":
    # Update these paths to match the actual file names generated by your Unity script!
    file_list = [
        # "Data/Telemetry_0kg_Grab1_010222.csv"  # Empty hand (0 kg)
        # "Data/Telemetry_2kg_Grab2_225728.csv"  # 2 kg
        # "Data/Telemetry_3kg_Grab2_230107.csv"   # 3 kg
        "Data/0kg curls 5th March/Telemetry_0kg_Grab1_001536.csv"  # Empty hand (0 kg)
    ]
    
    # The labels that will appear in the legend
    weight_labels = ["0.0"]
    
    plot_weight_comparison(file_list, weight_labels)